[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# 环境变量注入到前端
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 为生产环境注入环境变量
[[plugins]]
  package = "@netlify/plugin-env-vars"

# SPA路由重定向
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
